version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: barbershop_db
    environment:
      MYSQL_DATABASE: barbershop_db
      DB_URL: jdbc:mysql://localhost:3307/barbershop_db
      MYSQL_USER: barber
      MYSQL_PASSWORD: barber123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"